services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5555:5432'

  redis:
    image: 'redis:7.4.0-alpine'
    ports:
      - '6666:6379'
#    environment:
#      REDIS_PASSWORD: password