-- liquibase formatted sql

-- changeset imkrasnyukov:1728042396982-1
CREATE TABLE contact_info
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    method    VARCHAR(255)                            NOT NULL,
    data      VARCHAR(255)                            NOT NULL,
    person_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_contact_info PRIMARY KEY (id)
);

CREATE TABLE job_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company    VARCHAR(255)                            NOT NULL,
    position   VARCHAR(255),
    is_current BOOLEAN                                 NOT NULL,
    person_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_job_info PRIMARY KEY (id)
);

CREATE TYPE notification_status AS ENUM ('PENDING', 'SUCCESS', 'FAILURE');

CREATE TABLE notifications
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content VARCHAR(255),
    chat_id VARCHAR(255)                            NOT NULL,
    status  notification_status                     NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TYPE person_gender AS ENUM ('MALE', 'FEMALE', 'OTHER');

CREATE TABLE person
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255)                            NOT NULL,
    middle_name VARCHAR(255),
    last_name   VARCHAR(255),
    gender      person_gender,
    settings_id BIGINT,
    birth_date  date,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE person_settings
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notify_on_birthday BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_person_settings PRIMARY KEY (id)
);

ALTER TABLE person
    ADD CONSTRAINT uc_person_settings UNIQUE (settings_id);

ALTER TABLE contact_info
    ADD CONSTRAINT FK_CONTACT_INFO_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE job_info
    ADD CONSTRAINT FK_JOB_INFO_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE person
    ADD CONSTRAINT FK_PERSON_ON_SETTINGS FOREIGN KEY (settings_id) REFERENCES person_settings (id);

CREATE INDEX idx_contact_info_person_id ON contact_info (person_id);

CREATE INDEX idx_job_info_person_id ON job_info (person_id);
